# Generated by Django 4.1.3 on 2022-11-21 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0002_remove_friend_a_friend_friendid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friendId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId', to=settings.AUTH_USER_MODEL),
        ),
    ]
