# Generated by Django 4.1.3 on 2022-11-21 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_user'),
        ('friend', '0003_alter_friend_friendid_alter_friend_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friendId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendId', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId', to='customer.customer'),
        ),
    ]
